### ISSUE TITLE
Make the vacate plan polling frequence configurable

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#121]
## Overview
At the moment during the vacate operation, we poke the plan API every one second for each instance moved. This practically means that if we move 20 instances in parallel we send 20 Plan API requests per second.

Although this was done in purpose and it was a collaborative decision, it seems that our API is struggling some times. It would be great if we can do the following
1. Examine if it makes sense to increase the default polling frequency
2. Add an optional flag to allow operators adjust it accordingly

@marclop Please add some context on the way `vacate` works atm in terms of how we handle `404` errors and how this will impact the total time a vacate will take to complete, or any other consideration you might have.

**Comment by marclop** [comment]
I'll address point 1 in a rather small PR, the second configurable options for plan polling will come in later as they're a bit more work.
