### ISSUE TITLE
Support for Elastic Cloud SaaS

### ISSUE THREAD

**Issue by madisonb** [elastic/ecctl#129]
## Overview

I would like to requst the ability to control [Elastic Cloud SaaS](https://cloud.elastic.co/home) deployments. As heavy users of your cloud offering over running our own ECE environment, it would be great to interact with cloud's api in the same manner I could with this project.

## Possible Implementation

Additional documentation surrounding how to connect to the Elastic Cloud service when doing the initial configuration

## Testing

n/a

## Context

As noted above, we do not run our own Elasticsearch clusters, and thus must manually configure our clusters in the cloud ui. It would be great to be able to tie all of our other automation (ansible, terraform, etc) into Elastic as well.

## Your Environment

Note that I have a 2FA credential to log in to https://cloud.elastic.co, here is my output of trying to configure ecctl.

Via un/pw
```
$ ecctl init
Welcome to the Elastic Cloud CLI! This command will guide you through authenticating and setting some default values.

Missing configuration file, would you like to initialise it? [y/n]: y
Enter the URL of your ECE installation: https://cloud.elastic.co

What default output format would you like?
  [1] text - Human-readable output format, commands with no output templates defined will fall back to JSON.
  [2] json - JSON formatted output API responses.

Please enter a choice: 1


Which authentication mechanism would you like to use?
  [1] API Keys (Recommended).
  [2] Username and Password login.

Please enter your choice: 2

Type in your username: <removed>
Type in your password:

failed to login with user/password: unknown error (status 404): {resp:0xc00038e000}
````

Via JWT grabbed from logging in
```
$ ecctl init
Welcome to the Elastic Cloud CLI! This command will guide you through authenticating and setting some default values.

Missing configuration file, would you like to initialise it? [y/n]: y
Enter the URL of your ECE installation: https://cloud.elastic.co

What default output format would you like?
  [1] text - Human-readable output format, commands with no output templates defined will fall back to JSON.
  [2] json - JSON formatted output API responses.

Please enter a choice: 1


Which authentication mechanism would you like to use?
  [1] API Keys (Recommended).
  [2] Username and Password login.

Please enter your choice: 1

Paste your API Key and press enter:

{
    "errors": [
        {
            "message": "The supplied authentication is invalid",
            "code": "root.unauthenticated"
        }
    ]
}
```

Note that I cannot find an actual "API Key" button in the cloud console, so JWT was my next best guess.

Thanks!

**Comment by marclop** [comment]
Hi Madison,

Thanks for spending the time raising a GitHub issue. As you've already seen for yourself there's currently no way to use `ecctl` with ESS (Elastcsearch Service) or Elastic Cloud as it is known.

Note that the main README.md file states:

```markdown
Note that, right now, `ecctl` targets ECE installations only. There are, however, plans to support public Elasticsearch Service API in the future.
```

We'll support Elastic Cloud in the future, as of when it's still a bit fuzzy at the moment, but a future version will in fact support Elasticsearch Service's API through API Keys as an authentication mechanism, after Elasticsearch Service supports API keys in the (near) future.

Sorry for the inconvenience but at this moment, ecctl is not compatible with our service Elasticsearch Service authentication mechanisms, as the README.md currently states.

**Comment by madisonb** [comment]
@marclop Thanks for the reply - I understand the current implementation isn't available yet, but I just wanted to let your team know that this is a requested feature of the community so you could track and prioritize it when the time comes.

You may want to consider clarifying this summary line of the repo (at the top): 

```
Elastic Cloud Control, the official Elastic Cloud and ECE command line interface`
```
As I think it gives the impression of _both_ Elastic Cloud and ECE offering. Everything else seems fine.

**Comment by marclop** [comment]
@madisonb Elastic Cloud (ESS) is now officially supported, this issue can be closed.
