### ISSUE TITLE
Need command for listing runners under platform

### ISSUE THREAD

**Issue by axrayn** [elastic/ecctl#148]
## Overview
It's great that there's an easy CLI tool for listing this API information, but I noticed when I was testing today that I couldn't simply:
`ecctl platform list runners --all`
to list all the runners in our ECE environment.

We can list all allocators, constructors, and proxies, so any chance we can get runners added to the list please?

**Comment by marclop** [comment]
Hi @axrayn, thanks for opening an issue.

I will add your request to the current milestone to add the command. The command will be `eecctl platform runner list` rather than `list runners`
