### ISSUE TITLE
Only suggest to use API key as authentication mechanims

### ISSUE THREAD

**Issue by zanbel** [elastic/ecctl#157]
ESS will not support username and password to authenticate and in general API keys are the recommended way to authenticate. Would suggest to only suggest to use API key in the init wizard and document an exception for `admin` and `readonly` pre-configured ECE users that can not manage API keys.

**Comment by Kushmaro** [comment]
@zanbel thinking about this one - since we have an API Key limitation around LDAP authentication, i'm not sure if this won't be problematic for some folks.

I vote for allowing user/pass on ECE instances (i.e, when not configured for work with ESS)

**Comment by karencfv** [comment]
Heya @Kushmaro @zanbel, was something decided about this issue? Should we move forward with it?

**Comment by Kushmaro** [comment]
@karencfv thanks for checking,
yes we should move forward here with disabling user/pass for ESS only.

For ECE we'd still want to allow user/pass due to the LDAP consideration and the fact that currently, LDAP users are unable to create a key. user/pass would work for such users.
