### ISSUE TITLE
[ESS API Support] Hide some platform commands from help

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#160]
When working with ecctl against ESS, we should hide some of the platform commands in the help section, at least.

## commands that should be hidden
- platform allocator
- platform constructor
- platform enrollment-token
- platform info 
- platform instance-configuration
- platform proxy
- platform repository
- platform role
- user (no user mgmt in ess currently)

## commands that should be kept
- platform deployment-template list/show 
- platform stack list/show

Autocomplete command would still return all the above but should return 401 if tried

**Comment by ppapapetrou76** [comment]
@Kushmaro this is something that is brought for the first time to our attention. Can you please elaborate a bit more? I mean I understand the issue but users won't be able to get information from those commands. They will get `401`

What you are describing actually is to deliver a different version of `ecctl` for `ess`

**Comment by Kushmaro** [comment]
> @Kushmaro this is something that is brought for the first time to our attention. Can you please elaborate a bit more? I mean I understand the issue but users won't be able to get information from those commands. They will get `401`
> 
> What you are describing actually is to deliver a different version of `ecctl` for `ess`

Discussed this one with @marclop , he'll check if its possible. 
if loe isn't high, we should do it IMO to improve ecctl<->ESS usage experience
if loe is high, we could settle for returning 401s
