### ISSUE TITLE
[ESS API Support] Handle regions in config when ESS is configured

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#162]
## Original issue
In case a user opts to use ESS in the init flow (#159), we should query for a default region and handle it in the ecctl configuration file like we did in the pre-beta1 release

when configured with ece, we should either just used a default non-meaningful region, or ignore this flag completely 

## Update

We chatted about this yesterday and agreed that the desired thing would be to query an API endpoint and print a list of available regions, said endpoint is not available today so in the meantime maintaining a static list of providers is low effort and a quick win, any time a new release of ecctl is shipped, new regions can be included which makes it a valid distribution mechanism.

**Comment by zanbel** [comment]
Want to expand the scope of the issue a bit and also add the following.
1. Region config field / param: I think this is what Omer is suggestions, but just to make it more explicit, I would suggest to always have a region field in the configuration but in case of ECE it should set to "ece" and behavior should be consistent if the user will use a `--region ece`. Reason this is important to allow users to submit `ecclt deployments list --host $MY_ECE_URL --region ece` even when a default region is configured. 
2. Global vs. regional resources: even if configure to work with ESS API some resources will be global. For example certain account level configuration such as traffic filter rules. We need to identify which resources are global and which are regions and build this logic to be easily configurable and discoverable.

**Comment by marclop** [comment]
We chatted about this yesterday and agreed that the desired thing would be to query an API endpoint and print a list of available regions, said endpoint is not available today so in the meantime maintaining a static list of providers is low effort and a quick win, any time a new release of ecctl is shipped, new regions can be included which makes it a valid distribution mechanism.
