### ISSUE TITLE
Show a user-friendly error when config file doesn't exist or is not readable

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#220]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
When the config file used does not exist, the user should be informed with a user-friendly message

## Current Behavior
No error is reported. Instead, a not-very-helpful message is displayed
```
$ ecl platform region list --config wrong-file
1 error occurred:
	* apikey or user and pass must be specified
```

## Possible Solution
Check for config file existence and show a user-friendly message

## Steps to Reproduce
Just run any command by providing a config file value pointing to a file that doesn't exist

## Context
Maybe this is happening also even if the config file exists but its contents cannot be read.
I assume we need to handle that case too

## Your Environment
* Version used: 1.0.0-beta2

**Comment by marclop** [comment]
Requires https://github.com/elastic/cloud-sdk-go/pull/81 to be merged
