### ISSUE TITLE
[UX] explicitly require ecctl initialization

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#223]
In ecctl-beta2, if a command is run without ecctl having an init file, the following error message is received:
![image](https://user-images.githubusercontent.com/10343929/77255006-23700380-6c6d-11ea-9392-9134c2a3d8f2.png)

**Lets please add text that requires ecctl to be initialized.** 

Something along the lines of:
"apikey or user and pass must be specified using the ecctl init command"

**Comment by marclop** [comment]
@Kushmaro How does this look:

## Option 1

```console
$ ecctl user
uninitialized ecctl config file, please use "ecctl init" to initialize it: 1 error occurred:
	* invalid configuration options specified: apikey or user and pass must be specified
```

## Option 2

```console
$ ecctl user
Uninitialized ecctl config file, please use "ecctl init" to initialize it
invalid configuration options specified: 1 error occurred:
	* apikey or user and pass must be specified
```

**Comment by Kushmaro** [comment]
thanks @marclop 
I don't a specific preference :) both are fine, main issue was to call out that the config file is missing
