### ISSUE TITLE
Add a flag based deployment update

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#225]
## Description
Just like the `deployment create` [command](https://github.com/elastic/ecctl/pull/224) the `deployment update` command should work with flags as well as a JSON definition.

Some refactoring of the {kibana | apm | appsearch} creation will have to take place as well. 

For now each resource type that is being created makes a call to retrieve the deployment template definition. This is far from ideal, but the deployment {kibana | apm | appsearch} create commands use the same functions to update deployments with new instances.
**Update: The get deployment template api call does not work in ESS, a new way of retrieving information must be used.**

The `deployment {kibana | apm | appsearch} create` commands should be integrated into the deployment update command. This will address the above issue and have the deployment update command act in a similar way to the deployment create command with the newly introduced flags.

**Comment by karencfv** [comment]
This issue is temporarily halted until all users have read permissions for deployment templates.

Related: https://github.com/elastic/ecctl/pull/239

**Comment by Kushmaro** [comment]
@karencfv @marclop can we do something about this one since MS39 will be deployed with Sha's deployment-template API exposed, or is there an issue there with the permission model?

**Comment by karencfv** [comment]
Hi @Kushmaro this issue can be worked on if Sha's PR is included in MS39. I'll remove the "blocked" label :)

**Comment by karencfv** [comment]
Scratch that, this is for the `ecctl deployment update` command, I got confused and thought this issue was for `ecctl deployment create`. 
This issue can be worked on, but after https://github.com/elastic/ecctl/issues/295, as otherwise there would be duplicated work :)

**Comment by marclop** [comment]
I'm not sure this applies anymore, specially with Terraform covering more and more use cases for us.

**Comment by karencfv** [comment]
I think the `deployment show <id> generate-update-payload` flag is enough as well. We can open this issue again if there is enough demand for this functionality
