### ISSUE TITLE
deployment template list not working for Cloud Saas

### ISSUE THREAD

**Issue by 111andre111** [elastic/ecctl#229]
## Expected Behavior

It should display the possible templates

## Current Behavior

At the moment this does not work out for Cloud SaaS.

In #221 I got the hint about the `list` parameter.
`ecctl platform deployment-template list`
I get the error message:
```
<html><title>404: Not Found</title><body>404: Not Found</body></html>
```
I enabled verbose and obviously the resulting API call doesn't seem to work against Cloud SaaS
```
GET /api/v1/platform/configuration/templates/deployments?format=cluster&show_hidden=false&show_instance_configurations=false HTTP/1.1
Host: api.elastic-cloud.com
...

====================  End of Request #0  ====================
==================== Start of Response #0 ====================
HTTP/1.1 404 Not Found
...
<html><title>404: Not Found</title><body>404: Not Found</body></html>
```

Reference:
https://github.com/elastic/ecctl/issues/221

**Comment by karencfv** [comment]
Hi @111andre111! Thank you for taking the time to open this issue :) the deployment template commands are meant for ECE only. I have added the corresponding text that mentions that

**Comment by 111andre111** [comment]
@karencfv Ok, got it. But how will a user know what template type can be used in the case of ESS Cloud?

**Comment by karencfv** [comment]
@111andre111 For the time being they will be directed to our documentation to find this information. Both here -> https://www.elastic.co/guide/en/cloud/current/ec-getting-started-templates.html and here -> https://www.elastic.co/guide/en/cloud/current/ec-regions-templates-instances.html (this link doesn't work yet)
