### ISSUE TITLE
delete deployment does not working Cloud Saas

### ISSUE THREAD

**Issue by 111andre111** [elastic/ecctl#231]
## Expected Behavior

I want to be able to a certain deployment.

## Current Behavior

At the moment this does not work out for Cloud SaaS.

`ecctl deployment delete <cloudID>`
I get the error message:
```html
<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>
```
I enabled verbose and obviously the resulting API call doesn't seem to work against Cloud SaaS
```
==================== Start of Request #0 ====================
DELETE /api/v1/deployments/ad8f4f9ea6bfe5e875b851de2bdc0858 HTTP/1.1
Host: api.elastic-cloud.com


====================  End of Request #0  ====================
==================== Start of Response #0 ====================
HTTP/1.1 405 Method Not Allowed
Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE

<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>
====================  End of Response #0  ====================
<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>
```

**Comment by karencfv** [comment]
Hi @111andre111! Thank you again for taking the time to open this issue, we really really appreciate it :) the deployment delete command is meant for ECE only. I have added the corresponding text that mentions that

**Comment by 111andre111** [comment]
@karencfv So do I understand correctly, that for the use case ESS Cloud, I can create deployments, but I cannot delete them again per ecctl?

**Comment by karencfv** [comment]
@111andre111 yes, but you can shut them down with `ecctl deployment shutdown <deployment-id>` which by all intents is the same as delete except for the fact that it won't delete all the deployment's definitions

**Comment by 111andre111** [comment]
@karencfv Perfect, that works. Unfortunately the documentation does not reflect that for the moment, that in case we talk about ESS, shutdown means delete the instance.
