### ISSUE TITLE
Release v1.0.0-beta3

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#276]
## Version to be released

v1.0.0-beta3

## Checklist

- [x] Verify a cloud-sdk-go release with the same version has been made.
- [x] Update the cloud-sdk-go dependency. #269 
- [x] Update `VERSION` environment variable in the Makefile and generate changelog. #273 
- [x] Execute the release.
- [x] Create release branch for documentation.
- [x] Modify the conf.yaml file in the docs repository to add the release branch. https://github.com/elastic/docs/pull/1840
- [x] Run a full doc rebuild.
- [x] Celebrate :tada:

**Comment by karencfv** [comment]
@elastic/cloud-delivery @Kushmaro @zanbel We'll now be using these issues to track ecctl releases. This will also be a good place to keep track of any discussions regarding each release :)

**Comment by zanbel** [comment]
Thanks Karen! Since ecctl release is fairly quick @Kushmaro and I chatted yesterday and wanted to suggest that will execute the release procedure in tandem with releasing ESS API, which should happen 2 - 3 days after MS 36.

**Comment by karencfv** [comment]
Thanks @zanbel, I was chatting with @marclop earlier and we were thinking it'd be a good idea to finish up to step 4 of the checklist once we have feedback from you or @Kushmaro on anything you think we might be missing. 

It would be sort of a "silent ecctl release". Once the public API is ready to be released, we would finish the rest of the steps which are basically just making the release notes and documentation available. What do you think?

**Comment by karencfv** [comment]
This would also allow us to continue our work in ecctl so we are not held back with the release. :)

**Comment by Kushmaro** [comment]
Thanks @karencfv , yes we can now release ecctl-beta3 binaries

**Comment by karencfv** [comment]
All done here! I've verified links etc and all works fine 🎉
