### ISSUE TITLE
ESS is not really the default option when using `ecctl init`

### ISSUE THREAD

**Issue by zanbel** [elastic/ecctl#292]
When using the `ecctl init` wizard to config the client the first step is to decide which product you want to use between ESS, ECE, and EESP. ESS is meant to be the default option but when hitting return the same step reappears.

This is super minor :)

**Comment by Kushmaro** [comment]
@zanbel I'm aware of this one, at the time @karencfv mentioned it would be a bit of a headache to make the library used to create those menu selections to act differently, so we kept the current behavior due to a high effort-to-problem ratio

**Comment by marclop** [comment]
Can we close this?
