### ISSUE TITLE
Partial update with "ecctl deployment update --prune_orphans=false"

### ISSUE THREAD

**Issue by yokawasa** [elastic/ecctl#319]
## Question

I have an existing deployment with the following definition ( `...` = some settings ):
```json
{
  "name": "My Deployment",
  "resources": {
    "elasticsearch": [
      {
        "region": "ap-northeast-1",
        "ref_id": "elasticsearch",
        "plan": {
          "cluster_topology": [
            {
              "elasticsearch": {
                "system_settings": {  ...  },
                "user_bundles": [ ... ],
                "enabled_built_in_plugins": [ ... ]
              },
              "node_type": { ... },
              "instance_configuration_id": "aws.data.highcpu.m5",
              "zone_count": 1,
              "size": {
                "resource": "memory",
                "value": 122880
              }
            }
          ]
        }
      }
    ],
    "kibana": [ ... ],
    "apm": []
  }
}
```

I want to change only the size of memory, let's say, from 122880 to 61440, then I tried to update the cluster with `ecctl deployment update` and the following payload. However NOT only node size change BUT also user bundles & plugins removal were planned (please see the snapshot below), thus I canceled the deployment change. Is this an expected behabior?? My expectation is to update only the size of node, NOT to change or remove anything else. 

```json
{
  "name": "My Deployment",
  "prune_orphans": false,
  "resources": {
    "elasticsearch": [
      {
        "region": "ap-northeast-1",
        "ref_id": "elasticsearch",
        "plan": {
          "cluster_topology": [
            {
              "node_type": {
                "data": true,
                "master": true,
                "ingest": true,
                "ml": false
              },
              "instance_configuration_id": "aws.data.highcpu.m5",
              "zone_count": 1,
              "size": {
                "resource": "memory",
                "value": 61440
              }
            }
          ]
        }
      }
    ]
  }
}
```

![スクリーンショット 2020-06-23 8 45 38](https://user-images.githubusercontent.com/82332/85345925-d2530280-b52e-11ea-88ec-7337e74eee2f.png)

**Comment by karencfv** [comment]
Thank you for opening up this issue @yokawasa. 

This is the expected behaviour. Prune orphans only relates to separate resources. This means that if, for example, you didn't specify Kibana or APM at all in your JSON definition there will be no changes in these resources. Once you've specified a resource (in this case Elasticsearch), every change in the definition for that resource will be applied. In this case the bundles and plugins were removed from the definition so those changes were applied.

I hope this answers your question :)

**Comment by yokawasa** [comment]
@karencfv thanks alot for the comment! Perfectly understood!
