### ISSUE TITLE
Release v1.0.0

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#349]
## Version to be released

v1.0.0

## Checklist

- [x] Verify a cloud-sdk-go release with the same version has been made. https://github.com/elastic/cloud-sdk-go/pull/184
- [x] Update the cloud-sdk-go dependency. https://github.com/elastic/ecctl/pull/358
- [x] Update `VERSION` environment variable in the Makefile and generate changelog. https://github.com/elastic/ecctl/pull/350
- [x] Execute the release.
- [x] Create release branch for documentation.
- [x] Modify the conf.yaml file in the docs repository to add the release branch.
- [x] Run a full doc rebuild.
- [x] Celebrate :tada:

**Comment by Kushmaro** [comment]
@karencfv can you please provide with the bits download link + sha sum doc link so I can update marketing?

**Comment by karencfv** [comment]
Heya @Kushmaro, You can find that information here https://github.com/elastic/ecctl/blob/master/notes/v1.0.0.md 
Just a heads up that we've not actually released anything yet, so those links will be broken

**Comment by Kushmaro** [comment]
Yep, @karencfv I know :) Just want to be able to stage the links for marketing

**Comment by marclop** [comment]
`ecctl` has been released as part of the `2.6.0` release!
