### ISSUE TITLE
docs: Synopsis and Short description duplicated in generated .md files

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#351]
## Description
When no `Long` description is provided in the command, the documentation 
generator duplicates the `Short` description and prints it twice.

![Screen Shot 2020-07-22 at 7 10 33 PM](https://user-images.githubusercontent.com/7670244/88145784-141aba00-cc4f-11ea-91d1-645cdb404f94.png)

**Comment by karencfv** [comment]
Reading the code that generates the markdown, it looks like this format is by design https://github.com/spf13/cobra/blob/master/doc/md_docs.go#L61-L70.

The simplest way to fix this issue by only using `Long` description if we don't want to have `Long` and `Short`. I tried this approach with the command in the description:

<img width="299" alt="Screen Shot 2020-07-22 at 7 15 47 PM" src="https://user-images.githubusercontent.com/7670244/88146280-c5215480-cc4f-11ea-990c-a547ca88e294.png">

What do you think about this approach @nrichers? Is this what you had in mind? (Asking before undertaking the journey of changing all commands that need the change 😄 )

cc @marclop

**Comment by nrichers** [comment]
@karencfv this does fix the text duplication, which by itself is a huge improvement already! 

Looking at examples like https://www.elastic.co/guide/en/elasticsearch/reference/6.8/certutil.html, the ideal solution would be to move  the text before the command syntax above the **Synopsis** heading, but I would imagine that is a much more involved solution.  

An alternative might be to use your solution but to also hide the **Synopsis** heading. Effectively, the output would look like this: 

![image](https://user-images.githubusercontent.com/15148011/88230777-db1b1f00-cc27-11ea-93c5-e6bfdbb43303.png)

Would that work for you? This tweak would also avoid the double heading (**ecclt development** followed immediately by **Synopsis** which looks a bit odd to me).

**Comment by karencfv** [comment]
Thanks for the input @nrichers! The solution I proposed would only affect the commands that have duplicated text. All other commands would stay the same. Hiding the **Synopsis** heading will affect commands that do not have duplicated text.

The documentation generator uses the information provided in the `Command` struct which has several fields:

```go
var createCmd = &cobra.Command{
	Use:     "create {--file | --es-size <int> --es-zones <int> | --topology-element <obj>}",
	Short:   "Creates a deployment",
	Long:    createLong, //createLong is a variable which contains a large amount of text
	Example: createExample, //createExample is a variable which contains a large amount of text
```

It takes the text from `Short` and uses that for the text underneath the title of the command. The `Long` section is used to fill in the text for **Synopsis**, and `Example` for the **Examples**. When the `Long` field is empty, it takes whatever is in `Short` and [fills in](https://github.com/spf13/cobra/blob/master/doc/md_docs.go#L61-L70.) **Synopsis** with that. For the above code, the generated Markdown looks like this:

<img width="372" alt="Screen Shot 2020-07-23 at 10 30 12 AM" src="https://user-images.githubusercontent.com/7670244/88235702-88953d80-cccf-11ea-8ae5-014a52a6ec92.png">

Since the `Short` field is the only one it leaves empty if not populated in the struct, I suggested to only use the `Long` field in the cases where it wasn't necessary to have a `Short` and `Long` description.

Since the markdown generator is not our own code, and is part of the CLI framework we need to work with their design decisions unfortunately :( 

I can write our own Markdown generation code if this is something that is really important to fix. Although, I prefer to use the tooling that is provided with our CLI framework. This means it's less code we have to maintain.

Let me know what you think!

**Comment by nrichers** [comment]
@karencfv thank you, I appreciate the added explanation! Let me simply approve your PR as is, it's a fantastic improvement over what we had. Agreed on staying within the framework.

I think where I was going with my comment is that removing the duplication of the text is what we want, but you can sort of see the remnants of what was there by the double heading. And even where we do actually have content for both `short` and `long`, there's still some form of duplication. E.g. in your screenshot, does the `short` under the title actually add value when you repeat the same text under the `long` and then add more relevant content? If you look at what some other Elastic products do, they seem to put the content from the `long` under the title and then the actual `long` is just the syntax diagram, which sometimes can be quite ... long.

I don't actually have the answer here, but I would welcome the chance to talk about this some more the next time we have our sync. For ecctl 1.0.0, I would call this done.

**Comment by karencfv** [comment]
So it looks like my solution wasn't a good solution at all  :( It works for the markdown files, but it erases all the descriptions for the `--help` command.

```
$ go run main.go --help
Elastic Cloud Control

Usage:
  ecctl [command]

Available Commands:
  auth        
  deployment  
  generate    
  help        Help about any command
  init        
  platform    
  stack       
  user        
  version  
```

I think we're going to have to do what Helm does and [manually write out](https://helm.sh/docs/helm/helm_show/) a different description for `Short` and `Long` for each command.

Unfortunately I don't think we'll have time to finish that before GA. We might just have to do this slowly until we finish all the commands.

**Comment by karencfv** [comment]
Will unassign myself as this is a pretty big issue and it needs to be re-assessed
