### ISSUE TITLE
Role list is failing with json unmarshal error

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#391]
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
`ecctl platform role list` should return the list of roles

## Current Behavior
`ecctl platform role list` returns the error `json: cannot unmarshal string into Go struct field Metadata.values.role.meta.version of type int32`

## Possible Solution
Something is not synced with the api swagger definition. I ran `make swagger` in the cloud-sdk-go but nothing has been changed so I'm 🤔 

## Steps to Reproduce
Just run `ecctl platform role list` against a staging region - production works fine for now so I guess something was broken/changed in ms46.

## Context
This bug is blocking the implementation/testing of `ecctl platform role update` command, which is blocking the complete syncing of roles through the deployer

**Comment by riccardomarinelli** [comment]
@ppapapetrou76 I am seeing this issue in QA currently https://rundeck.staging.getin.cloud/project/elastic-cloud-qa/execution/show/8938554#output

```
[2020-09-28T22:15:47.917Z] [:INFO] Listing roles in region [aws-eu-west-1]
1 error occurred: push roles operation: 1 error occurred:
	* pull roles: diff roles: diff roles from aws-eu-west-1 : json: cannot unmarshal string into Go struct field Metadata.values.role.meta.version of type int32
ddfb108dec0d8f6dcf17a4489350fde28e038f2d61c43744d9dae8b23dcff150
Result: 255
Failed: NonZeroResultCode: Result code was 255
Execution failed: 8938554 in project elastic-cloud-qa: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [rundeck.staging.getin.cloud: NonZeroResultCode: Result code was 255 + {dataContext=MultiDataContextImpl(map={ContextView(node:rundeck.staging.getin.cloud)=BaseDataContext{{exec={exitCode=0}}}, ContextView(step:1, node:rundeck.staging.getin.cloud)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {rundeck.staging.getin.cloud=[NonZeroResultCode: Result code was 255 + {dataContext=MultiDataContextImpl(map={ContextView(node:rundeck.staging.getin.cloud)=BaseDataContext{{exec={exitCode=0}}}, ContextView(step:1, node:rundeck.staging.getin.cloud)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]
```

how can we update it for QA? thanks

**Comment by stj** [comment]
@ppapapetrou76 another issue in QA last night https://rundeck.staging.getin.cloud/project/elastic-cloud-qa/execution/show/9038037

```
2 errors occurred:
	* service deployment - check running container tag: cannot find a valid container on runner i-083dfd2aec3b94847 using container set tags [frontends] and container name tags [billing-service]
	* service deployment - check running container tag: cannot find a valid container on runner i-00ea592c90d23d905 using container set tags [frontends] and container name tags [billing-service]
d17b49a2c0446b1b53f308a7769e8cc54691eb6064165355a4cdb112b7b3c082
Result: 255
Failed: NonZeroResultCode: Result code was 255
```
