### ISSUE TITLE
--generate-update-payload flag for deployment show command doesn't show observability settings

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#407]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

**EDIT:** The original issue is not present in the master branch, it has been fixed with the latest cloud-sdk-go
update and this bug fix will be included in the next release.

What was still broken however, is the `--generate-update-payload` flag, which did not include observability settings
in the generated payload

## Expected Behavior
Running `ecctl deployment show <id>` should output everything in the settings block, not just traffic filter information.

## Current Behavior
When running  `ecctl --config ess deployment show <deployment-id> --verbose` for a deployment that has traffic filter and observability settings you can see the following output:

```console
ecctl --config ess deployment show f9c2c6a47f3f49dba60edc9a2b030de8 --verbose
Using config file: /Users/karen/.ecctl/ess.yaml
==================== Start of Request #0 ====================
GET /api/v1/deployments/f9c2c6a47f3f49dba60edc9a2b030de8?convert_legacy_plans=false&enrich_with_template=true&show_metadata=false&show_plan_defaults=false&show_plan_history=false&show_plan_logs=false&show_plans=false&show_security=false&show_settings=false&show_system_alerts=5 HTTP/1.1
<...>
"id" : "f9c2c6a47f3f49dba60edc9a2b030de8",
<...>
"settings" : {
    "ip_filtering_settings" : {
      "rulesets" : [
        "4e974d9476534d35b12fbdcfd0acee0a"
      ]
    },
    "traffic_filter_settings" : {
      "rulesets" : [
        "4e974d9476534d35b12fbdcfd0acee0a"
      ]
    },
    "observability" : {
      "logging" : {
        "destination" : {
          "deployment_id" : "cfd563de3b3d4883aa0f1b060174b81c",
          "ref_id" : "main-elasticsearch"
        }
      },
      "metrics" : {
        "destination" : {
          "deployment_id" : "cfd563de3b3d4883aa0f1b060174b81c",
          "ref_id" : "main-elasticsearch"
        }
      }
    }
  },
<...>
====================  End of Response #0  ====================
<...>
"id" : "f9c2c6a47f3f49dba60edc9a2b030de8",
<...>
"settings": {
    "ip_filtering_settings": {
      "rulesets": [
        "4e974d9476534d35b12fbdcfd0acee0a"
      ]
    },
    "traffic_filter_settings": {
      "rulesets": [
        "4e974d9476534d35b12fbdcfd0acee0a"
      ]
    }
  }
```

## Steps to Reproduce

1. Create a deployment with both traffic filter and observability settings
2. run `ecctl deployment show <deployment id> --verbose`

## Your Environment

* Version used: v1.0.0

**Comment by s-nel** [comment]
Note this affects `deployment update` request that includes deployment settings. E.g.

```
test-edit1.json
{
  "prune_orphans": false,
  "settings": {
    "observability": {
      "metrics": {
        "destination": {
          "deployment_id": "558bcdafbdbd421bb0f52a9a450eb881",
          "ref_id": "main-elasticsearch"
        }
      },
      "logging": {
        "destination": {
          "deployment_id": "558bcdafbdbd421bb0f52a9a450eb881",
          "ref_id": "main-elasticsearch"
        }
      }
    }
  }
}

ecctl --verbose deployment update $CLUSTER_ID -f test-edit1.json
Using config file: /Users/ed/.ecctl/config.json
==================== Start of Request #0 ====================
PUT /api/v1/deployments/22168e94cdb84d339d5f7801cbb8042e?hide_pruned_orphans=false&skip_snapshot=false&validate_only=false HTTP/1.1
Host: api.elastic-cloud.com
User-Agent: ecctl/v1.0.1
Content-Length: 24
Accept: application/json
Authorization: ApiKey Yk5DdG5YVUJITmdvY3V5bXFxTk46WjVfR3lDbjlRRkNiTlpGS2xxNWxDZw==
Content-Type: application/json
Accept-Encoding: gzip

{"prune_orphans":false}

```

**Comment by karencfv** [comment]
The `ecctl deployment update` command takes a `.json` file and applies the plan, so this bug will only affect `.json` files generated with `ecctl deployment show --generate-update-payload`

**Comment by edsyoo** [comment]
Thanks for the direction and confirmation, @karencfv and @s-nel!  I'll close this out as a bug and issue summary.
