### ISSUE TITLE
`deployment delete` fails against cloud.elastic.co

### ISSUE THREAD

**Issue by rhass** [elastic/ecctl#411]
## Readiness Checklist

- [x] I am running the latest version
- [ ] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
`ecctl deployment delete my-deployment-id` should delete a specified deployment.

## Current Behavior
The command returns this error instead:
```
[DELETE /deployments/{deployment_id}][404] deleteDeploymentNotFound  &{Errors:[]}
```

## Steps to Reproduce
1. Create a deployment
2. Get the deployment ID.
3. Attempt to delete the deployment with `ecctl deployment delete {id}`

## Context
I am trying to delete a deployment.

## Your Environment

* Version used: 1.0.1 (public binary)
* Environment name and version (e.g. Go 1.9): N/A
* Operating System and version: Linux x86-64

**Comment by karencfv** [comment]
Hi @rhass ! The `ecctl deployment delete` command is an ECE only command. There are some endpoints in the API which are not public and this is one of them.

A good way to find out if a command is only available for ECE is to use the `--help` flag after the command. It will show you a text that says `(Available for ECE only)`.

If you want to terminate deployments in ESS you should use the `ecctl deployment shutdown` command. Which will downscale a deployment and hide it.

**Comment by rhass** [comment]
Ah! Thanks!

**Comment by rhass** [comment]
@karencfv 

I was just thinking, perhaps a better user experience would be to make the `delete` a flag option of `shutdown` which is only applicable to ece. Eg: `ecctl shutdown --delete ece-deployment-id` and `ecctl shutdown ess-deployment-id`. 

Assuming `shutdown` works on ECE right now, this could improve the UX by making the same base command work for both ESS and ECE, while providing ECE users the option to delete the deployment.  However, I realize this is proposes a breaking change to the command line API since any scripts using `ecctl deployment delete` would have to be updated to `ecctl deployment shutdown --delete`.

**Comment by karencfv** [comment]
Thanks for the suggestion! Unfortunately we are out of beta now so we can't make breaking changes like that. Your idea would have definitely made it clearer though 🤔
