### ISSUE TITLE
release: Change the way we install hub

### ISSUE THREAD

**Issue by karencfv** [elastic/ecctl#412]
## Description
When running the release GH action there is an error due to  the 
geertvdc/setup-hub action we use to install hub. We should install
hub in some other way.

### Example
https://github.com/elastic/ecctl/runs/1495831047

**Comment by marclop** [comment]
I think in the long run we should look into doing the same with the new GitHub CLI `gh`. In the meantime we could enable the environment variable `ACTIONS_ALLOW_UNSECURE_COMMANDS` while we migrate.

**Comment by karencfv** [comment]
Fixed in https://github.com/elastic/ecctl/pull/443
