### ISSUE TITLE
Configure a web proxy for ecctl requests

### ISSUE THREAD

**Issue by Kushmaro** [elastic/ecctl#415]
## Feature request
The ability to configure a web proxy through which all ecctl commands will go through, instead of having to proxy the entire OS which ecctl operates under.

## Suggested solution
Keep details in ecctl configuration, and incorporate as part of the init flow

**Comment by marclop** [comment]
For what's worth, the Go HTTP client supports proxying by default when exporting the environment variable `HTTP_PROXY`:

```
$ export HTTP_PROXY="http://proxyIp:proxyPort"
```

**Comment by karencfv** [comment]
Closing this for now as we had a discussion about this functionality being part of Go itself. We can open up the issue again if needed.
