### ISSUE TITLE
Doesn't support macOS 11 (Big Sur)

### ISSUE THREAD

**Issue by andylow** [elastic/ecctl#417]
![image](https://user-images.githubusercontent.com/7241168/101724263-22c41980-3ae9-11eb-9742-37f712daca20.png)

**Comment by marclop** [comment]
As far as I can tell (by a quick google search on the error message) you need to re-install your CommandLineTools in MacOS, you can do so with, to be clear, this is provided without any assurances, I'm copy pasting solutions that seemed to work for other people, use at your own risk.

```
sudo rm -rf /Library/Developer/CommandLineTools
sudo xcode-select --install
```

_source: https://apple.stackexchange.com/questions/401899/homebrew-your-clt-does-not-support-macos-11-0_
