### ISSUE TITLE
"ecctl deployment template show --template-id" results in root.unauthorized.rbac error

### ISSUE THREAD

**Issue by simonclausen** [elastic/ecctl#423]
Running `ecctl deployment template show --template-id <id>` will fail consistently with an authorization related error message.

## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

The template config JSON to be printed.

## Current Behavior

The command errors and this message is printed:

```
api error: 1 error occurred:
	* root.unauthorized.rbac: The supplied authentication is not authorized to access this resource. Reason: [Missing required permissions].
```

## Context

This happens using credentials for users with "platform admin" role in ECE.

I've tried using both user/pass and API key `ecctl` config:

```
{
  "host": "https://admin.host/",
  "api_key": "<key>",
  "output": "text",
  "timeout": 30000000000,
  "insecure": false
}
```

```
{
  "user": "<user>l",
  "pass": "<pass>",
  "host": "https://admin.host/",
  "output": "text",
  "timeout": 30000000000,
  "insecure": false
}
```
For variations of users I've tried both local users and LDAP authentication backend users. For configuring `ecctl` for user/pass I've used "admin" and my usual LDAP administration user, which both seem to have access to everything as usual using the GUI. For the API key setup I've created a new local user to test with and created and API key on there.

I've tried this on two separate ECE instances, both running version 2.5.1.

## Versions

eccl:

```
Version:               v1.1.0
Client API Version:    2.8.0-ms48
Go version:            go1.15.2
Git commit:            a2293c25
Built:                 Thu 03 Dec 23:21:49 2020
OS/Arch:               darwin / amd64
```

ECE Platform: version 2.5.1

**Comment by simonclausen** [comment]
It just occurred to me to check the API docs to try to better understand what could be going on.

Seems like there is no `/api/v1/deployments/templates/{template_id}` endpoint for the ECE version we're running? It's not clear from the release notes or API docs in what version this was added.

**Comment by marclop** [comment]
This seems to have been added on the [`ECE 2.6.0`](https://github.com/elastic/cloud-sdk-go/blob/master/api/version/2.6.0.md). What version are you running?

**Comment by simonclausen** [comment]
Cheers - seems like I've found the issue :)
