### ISSUE TITLE
ecctl does not sort stack versions correctly

### ISSUE THREAD

**Issue by ckauf** [elastic/ecctl#427]
## Readiness Checklist
- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
When a deployment with `ecctl` is created it should select the newest version available, as stated in the [documentation](https://www.elastic.co/guide/en/ecctl/current/ecctl_deployment_create.html):
> When version is not specified, the latest available stack version will automatically be used.

## Current Behavior
Currently `ecctl` considers 7.9 newer then 7.10.

## Possible Solution
Sort the newest version on top

## Steps to Reproduce
1. Upload a Stack Pack for 7.10 and 7.9 to ECE
2. List deployments, notice 7.9 is sorted above 7.10
3. Create deployment without version parameter. `ecctl` will pick 7.9

```
$ ecctl stack list
VERSION   DELETED   ELASTICSEARCH IMAGE                                     KIBANA IMAGE                                     APM IMAGE
7.9.3     false     docker.elastic.co/cloud-assets/elasticsearch:7.9.3-0    docker.elastic.co/cloud-assets/kibana:7.9.3-0    docker.elastic.co/cloud-assets/apm:7.9.3-0
7.10.1    false     docker.elastic.co/cloud-assets/elasticsearch:7.10.1-0   docker.elastic.co/cloud-assets/kibana:7.10.1-0   docker.elastic.co/cloud-assets/apm:7.10.1-0
6.8.13    false     docker.elastic.co/cloud-assets/elasticsearch:6.8.13-0   docker.elastic.co/cloud-assets/kibana:6.8.13-0   docker.elastic.co/cloud-assets/apm:6.8.13-0

$ ecctl deployment create
Obtained latest stack version: 7.9.3
{
  "created": true,
  "id": "f826922063d2bd35a6678f6531843f01",
  "name": "f826922063d2bd35a6678f6531843f01",
  [...]
}
```

## Your Environment
* Version used: 1.1.0 installed via RPM

**Comment by karencfv** [comment]
Thanks for opening an issue @ckauf :)

This bug originated in our SDK and has been [fixed](https://github.com/elastic/cloud-sdk-go/pull/265). We have already [imported](https://github.com/elastic/ecctl/pull/418) the SDK version with the fix for the next release.

In the mean time you can build ecctl from source following these [instructions](https://github.com/elastic/ecctl/blob/master/CONTRIBUTING.md#build-ecctl-locally-with-your-changes).

**Comment by karencfv** [comment]
I will close this issue as the fix has already been merged.
