### ISSUE TITLE
Remove any ESS related references

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#43]
We need to remove any references to ESS - The following have been identified. It's a good idea to do a quick pass

1. In `init` command: “Enter the URL of the Elastic Cloud API or your ECE installation:”
2. `ecctl` help command: `--host string`  :  Base URL to use (default "https://api.elastic-cloud.com") should remove the default, ask for an `ecctl init`, or proper ECE host if one doesn’t exist.
3. Drop referencing regions, as they are ESS specific
4. Remove --region flag, and config file region reference

**Comment by marclop** [comment]
Resolves all points except `1`. Will fix it in an upcoming PR since the current seems a bit out of band
