### ISSUE TITLE
plugin option gets ignored

### ISSUE THREAD

**Issue by ckauf** [elastic/ecctl#430]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior
ecctl should generate a JSON including the `enabled_built_in_plugins` object

## Current Behavior
ecctl ommits the `enabled_built_in_plugins` object.

## Possible Solution
include `enabled_built_in_plugins` 

## Steps to Reproduce
1. Generate deployment JSON via `ecctl deployment create --es-size 16g --es-zones 2 --kibana-size 1g --kibana-zones 1 --version 7.10.1 --name testdepl --plugin "analysis-icu" --generate-payload | jq .resources.elasticsearch`
2. Notice missing `enabled_built_in_plugins` in the elasticsearch resource description.

## Context
Not being able to create deployments with `ecctl` without manually modifying the JSON

## Your Environment
* Version used:
ECE 2.7.1
ecctl:
Version:               v1.1.0
Client API Version:    2.8.0-ms48
Go version:            go1.15.2
Git commit:            a2293c25
Built:                 Thu 03 Dec 23:21:49 2020
OS/Arch:               darwin / amd64

**Comment by marclop** [comment]
I've opened https://github.com/elastic/cloud-sdk-go/pull/279 to fix it, once we update the module to the upcoming `v1.2.0` it'll be resolved.

**Comment by marclop** [comment]
`v1.2.0` has been released and this should be resolved. Closing.
