### ISSUE TITLE
Track the creation of a cluster "quietly"

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#435]
@gservat commented on [Mon Sep 30 2019](https://github.com/elastic/cloud-cli/issues/1009)

## Overview

So currently when you create a cluster you can use `--track` (i.e. `ecl` doesn't exit until the cluster has been fully created), which displays the result of every plan step + JSON blob **OR** you can omit the argument, which will submit the plan (and display the JSON blob) but you don't know when it's done.

What I'm proposing is a mix of the two options (i.e. track but quietly)

## Possible Implementation

What would be great is if `--track` would check if `--quiet` is set, in which case it should only display the resulting JSON blob and nothing else in the output. If `--quiet` is _not_ set, then it can behave as it does currently -- i.e. display the plan steps output + JSON blob at the end.

## Context
This came about as I was writing a script that would call `ecl` to create an ES cluster. I wanted to use `--track` so that I can enable Kibana on the cluster when it's done, however ideally the output of the `ecl` command (with `--track`) should _only_ display the JSON blob. Of course, there are workarounds, but not very pretty :-)

You could argue that there should be a way to trigger a cluster create with kibana enabled in one hit (maybe there is?), but I think this feature request is still valid for other use cases.

---

@marclop commented on [Mon Mar 09 2020](https://github.com/elastic/cloud-cli/issues/1009#issuecomment-596340243)

after https://github.com/elastic/cloud-sdk-go/pull/66  is merged, it'll be possible to do so.

**Comment by marclop** [comment]
@ppapapetrou76 @gservat you can create a deployment with any resources you'd like now via the deployments API. However, would you still like to see this feature worked into `ecctl`? If so, I'll add it to the backlog.

**Comment by ppapapetrou76** [comment]
@marclop I'm just the messenger 😄  I moved this ticket from `cloud-cli` repo so 🤷🏾 
Maybe @gservat who was the original author has something to say

**Comment by marclop** [comment]
@gservat ?

**Comment by gservat** [comment]
If you can create a deployment with the necessary resources now (i.e. ES + Kibana + ...) and you can call `ecl` to create it and display the resulting JSON blob (even if it creates it in the background), then I think that's good enough.

Is it possible to display the JSON blob and then use another command to "wait until it's fully created"? I don't have a use case right now but I can see it being useful to e.g. create a deployment with Kibana, get the JSON blob with the endpoints etc, wait until it's fully created, then hit the endpoints.

**Comment by marclop** [comment]
@gservat why not use the Terraform provider then? 🙂

**Comment by marclop** [comment]
I'm going to close this issue, I do not see a compelling reason to keep it open and the requested feature functionality is fuzzy at best.
