### ISSUE TITLE
Release v1.2.0

### ISSUE THREAD

**Issue by marclop** [elastic/ecctl#436]
## Checklist

- [x] Verify a cloud-sdk-go release with the same version has been made.
- [x] Update the cloud-sdk-go dependency.
- [x] Update `VERSION` environment variable in the Makefile and generate changelog.
- [x] Execute the release.
- [x] Create release branch for documentation.
- [x] Modify the conf.yaml file in the docs repository to add the release branch.
- [x] Run a full doc rebuild.
- [x] Alert marketing team to update downloads website with new links.
- [x] Celebrate :tada:

**Comment by Kushmaro** [comment]
Do we want to have a stab at automating the binary page like the ES team does in this release?

**Comment by marclop** [comment]
@Kushmaro do we need to alert anyone to update the binary in the website pages?

**Comment by karencfv** [comment]
I added the last bit on how to do that on the release doc https://github.com/elastic/ecctl/blob/master/developer_docs/RELEASE.md#update-downloads-website. Did either @alpar-t or @obierlaire do this bit?
