### ISSUE TITLE
Creating a deployment note requires a user id

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/ecctl#437]
## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

When running:

```
ecctl deployment note create $DEPLOYMENT_ID --comment "some comment here" --region="aws-eu-central-1"
```

I'd expect that a new note as specified by the value of the command line argument `--comment` is created for the deployment `$DEPLOYMENT_ID`.

## Current Behavior

The above command provides the output:

```
deployment note add: 1 error occurred:
	* user id cannot be empty
```

When running the above command with `--verbose`, we see:

```
Using config file: /Users/daniel/.ecctl/config.yaml
==================== Start of Request #1 ====================
GET /api/v1/deployments/DEPLOYMENT_ID_REDACTED?convert_legacy_plans=false&enrich_with_template=true&show_metadata=false&show_plan_defaults=false&show_plan_history=false&show_plan_logs=false&show_plans=false&show_security=false&show_settings=false&show_system_alerts=5 HTTP/1.1
Host: api.elastic-cloud.com
User-Agent: ecctl/v1.1.0
Accept: application/json
Authorization: [REDACTED]
Accept-Encoding: gzip


====================  End of Request #1  ====================
==================== Start of Response #1 ====================
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Connection: keep-alive
Content-Type: application/json
Date: Wed, 10 Feb 2021 07:53:01 GMT
Server: fac/[redacted]
X-Cloud-Resource-Created: 2020-01-24T10:56:55.362Z
X-Cloud-Resource-Last-Modified: 2021-02-01T17:02:34.945Z
X-Cloud-Resource-Version: 10
X-Ratelimit-Interval: 1 second
X-Ratelimit-Limit: 50
X-Ratelimit-Remaining: 49
X-Ratelimit-Reset: Wed, 10 Feb 2021 07:53:01 GMT
X-Request-Id: [REQUEST_ID_REDACTED]

[JSON BODY REDACTED]

====================  End of Response #1  ====================
deployment note add: 1 error occurred:
	* user id cannot be empty
```

## Steps to Reproduce

1. Create a configuration file in `~/.ecctl/config.yaml` (see contents below)
2. Find a deployment id, e.g. via `ecctl deployment list` (referred to as `$DEPLOYMENT_ID` below)
3. Run `ecctl deployment note create $DEPLOYMENT_ID --comment "some comment here" --region="aws-eu-central-1"`

`config.yaml`:

```yaml
host: https://api.elastic-cloud.com

# Credentials
api_key: API_KEY_REDACTED
```

## Your Environment

* Version used: 1.1.0
* Environment name and version (e.g. Go 1.9): `go version go1.15.7 darwin/amd64`
* Server type and version: N/A
* Operating System and version: `Darwin Kernel Version 19.6.0`
* Link to your project: N/A

**Comment by Kushmaro** [comment]
Hi @danielmitterdorfer thanks so much for spotting and opening this ticket.
Can you please elaborate on the use case for using ecctl in conjunction with deployment notes? 
what's the higher-level goal you're trying to achieve?

Can you also confirm that you're using ecctl in conjunction with ESS (if I understand correctly)?

**Comment by danielmitterdorfer** [comment]
>  Can you please elaborate on the use case for using ecctl in conjunction with deployment notes?

The Elasticsearch performance team owns a couple of Cloud clusters and in order to understand the cluster's purpose,  identifying a point of contact etc., we came up with some meta-data that we want to attach to each cluster when it is created. While it would be possible to do that via the admin UI, this is not scriptable and this is why we turned to ecctl which offers the `deployment note create` command.

> Can you also confirm that you're using ecctl in conjunction with ESS (if I understand correctly)?

Yes, that's correct.

**Comment by Kushmaro** [comment]
Thanks for the further details @danielmitterdorfer .

Unfortunately, we had a documentation bug, and this specific command is only available in case of using ECE (our on-premise version of Elastic Cloud)

We try to minimize such functionality gaps as much as we can, but we also miss them sometimes.

I'd think the larger use case you're describing here may be using metadata tags in conjunction with deployments. Which makes perfect sense of course. 

We have it on our radar, I can post back and update here if when it's available.

**Comment by danielmitterdorfer** [comment]
Oh, too bad it's not working for Elastic Cloud deployments (yet). Thanks for the feedback and looking forward to the day when it will be available. :)
