### ISSUE TITLE
[Staging][2.9.0-SNAPSHOT] ecl 1.4.0 cannot create deployments

### ISSUE THREAD

**Issue by ppapapetrou76** [elastic/ecctl#449]
@kuisathaverat commented on [Wed Feb 17 2021](https://github.com/elastic/cloud-cli/issues/1310)

I am trying to create a new deployment on the staging environment and I have found some issues, the payload seems to be wrong for the versions deployed.

## Readiness Checklist

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

A deployment is created

## Current Behavior

The deployment is not created and fails with the following error

```
The deployment creation returned with an error. Use the displayed request ID to recreate the deployment resources
Request ID: 2agzyd38vm1thksrn16dfjlawku9j7zjvzoffwaisk4p7lwrj5rrzp1mds8rwme8
api error: 1 error occurred:
	* deployments.unrecognized_topology_elements: Deployment plan definition includes topology element not supported by template [I/O Optimized]. Instance configuration: [Some(aws.data.highstorage.d3)], node types: [Some(ElasticsearchNodeType(Some(false),Some(true),Some(false),None))] (resources.elasticsearch[0])
```

## Steps to Reproduce

1. run  `ecl deployment create --name "es-oblt-test-ecl" --version "7.11.0" --es-size 4g --host https://admin.staging.foundit.no`

## Your Environment

* Version used: ecl 1.4.0
* Server type and version: Elastic cloud staging environment 2.9.0-SNAPSHOT

**Comment by marclop** [comment]
This was fixed in https://github.com/elastic/ecctl/pull/460 and will be released in the upcoming `v1.3.0`.
