### ISSUE TITLE
Release 1.5.0 for ECE 2.11.0

### ISSUE THREAD

**Issue by rhass** [elastic/ecctl#495]
## Version to be released
v1.5.0

## Checklist

The following actions must be performed in the order specified here.
For detailed instructions on all of the steps, read the release [documentation](https://github.com/elastic/ecctl/blob/master/developer_docs/RELEASE.md).

- [x] Verify a cloud-sdk-go release with the same version has been made.
- [x] Update the cloud-sdk-go dependency.
- [x] Update `VERSION` environment variable in the Makefile and generate changelog.
- [x] Execute the release.
- [x] Create release branch for documentation.
- [x] Modify the conf.yaml file in the docs repository to add the release branch.
- [x] Run a full doc rebuild.
- [x] Alert marketing team to update downloads website with new links.
- [x] Celebrate :tada:

**Comment by rhass** [comment]
@marclop It looks like the release is already done, should we just close this?

**Comment by marclop** [comment]
All done but the marketing doc to update the Elastic downloads page, let me know if you need help doing that. It should be in the ECE release issue checklist.
