### ISSUE TITLE
[discuss] Configuration and API Key documentation

### ISSUE THREAD

**Issue by gtback** [elastic/ecctl#505]
## Question

The [Configuring page](https://www.elastic.co/guide/en/ecctl/current/ecctl-configuring.html) talks about the precedence of configuration sources, and how to generate the config file, but doesn't explain where to get the API key that is needed for `ecctl init` ([this page](https://www.elastic.co/guide/en/cloud/current/ec-api-authentication.html) for ESS and [this section](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-restful-api-authentication.html#ece-api-keys) for ECE). It might be good to mention that above the `ecctl init` steps. For ESS we can link directly to https://cloud.elastic.co/deployment-features/keys .

I also think we'd prefer to de-emphasize the `--user` and `--pass` options (which I don't think work at all for ESS). But I didn't want to make those changes without discussing it first.

**Comment by marclop** [comment]
We should fix the lack of mentions on how to get the API key for sure.

Regarding the --user and --pass flags, I believe that's still something that's very relevant for our ECE customers and also something that is used for other internal tools that rely on the username and password still.

What ideas did you have in mind to de-emphasize the --user and --pass flags?

**Comment by gtback** [comment]
> What ideas did you have in mind to de-emphasize the --user and --pass flags?

I was thinking that we could find different examples of flags to use under the ["Before you begin"](https://www.elastic.co/guide/en/ecctl/current/ecctl-configuring.html#_before_you_begin) section, that apply to both ESS and ECE users. Looking at the output of `ecctl help`, I'm not sure what those would be. Maybe just add `--api-key` as well?

I just got confused initially about whether I would need a username and password, since the API key wasn't mentioned until I got to the `Paste your API Key` step.

**Comment by marclop** [comment]
> I was thinking that we could find different examples of flags to use under the "Before you begin" section, that apply to both ESS and ECE users. Looking at the output of ecctl help, I'm not sure what those would be. Maybe just add --api-key as well?

We could add `--output` and `--api-key` as examples in that document.

I think we could possibly add a link to https://cloud.elastic.co/deployment-features/keys in the `ecctl init` command after the ESS option has been select to ease things out.

```console
$ ecctl init
Welcome to Elastic Cloud Control (ecctl)! This command will guide you through authenticating and setting some default values.

Missing configuration file, would you like to initialise it? [y/n]: y

Select which type of Elastic Cloud offering you will be working with:
  [1] Elasticsearch Service (default).
  [2] Elastic Cloud Enterprise (ECE).
  [3] Elasticsearch Service Private (ESSP).

Please enter your choice: 1

Using "https://api.elastic-cloud.com" as the API endpoint.

Select a region you would like to have as default:

  GCP
  [1] us-central1 (Iowa)
  [2] us-east1 (S. Carolina)
  [3] us-east4 (N. Virginia)
  [4] us-west1 (Oregon)
  [5] northamerica-northeast1 (Montreal)
  [6] southamerica-east1 (São Paulo)
  [7] australia-southeast1 (Sydney)
  [8] europe-west1 (Belgium)
  [9] europe-west2 (London)
  [10] europe-west3 (Frankfurt)
  [11] asia-northeast1 (Tokyo)
  [12] asia-south1 (Mumbai)
  [13] asia-southeast1 (Singapore)

  AWS
  [14] us-east-1 (N. Virginia)
  [15] us-west-1 (N. California)
  [16] us-west-2 (Oregon)
  [17] eu-central-1 (Frankfurt)
  [18] eu-west-2 (London)
  [19] eu-west-1 (Ireland)
  [20] ap-northeast-1 (Tokyo)
  [21] ap-southeast-1 (Singapore)
  [22] ap-southeast-2 (Sydney)
  [23] sa-east-1 (São Paulo)

  Azure
  [24] eastus2 (Virginia)
  [25] westus2 (Washington)
  [26] westeurope (Netherlands)
  [27] uksouth (London)
  [28] japaneast (Tokyo)
  [29] southeastasia (Singapore)

Please enter your choice: 2

Create a new ESS API Key (https://cloud.elastic.co/deployment-features/keys) or
Paste your API Key and press enter:

```

**Comment by gtback** [comment]
> I think we could possibly add a link to cloud.elastic.co/deployment-features/keys in the ecctl init command after the ESS option has been select to ease things out.

This would be great! Even if people aren't reading the docs, they'll know what to do.
