### ISSUE TITLE
Release ecctl v1.7.0

### ISSUE THREAD

**Issue by obierlaire** [elastic/ecctl#531]
Related to https://github.com/elastic/dev/issues/1814
## Checklist

The following actions must be performed in the order specified here.
For detailed instructions on all of the steps, read the release [documentation](https://github.com/elastic/ecctl/blob/master/developer_docs/RELEASE.md).

- [x] Verify a cloud-sdk-go release with the same version has been made.
- [x] Update the cloud-sdk-go dependency.
- [x] Update `VERSION` environment variable in the Makefile and generate changelog.
- [x] Execute the release.
- [ ] Create release branch for documentation.
- [ ] Modify the conf.yaml file in the docs repository to add the release branch.
- [ ] Run a full doc rebuild.
- [ ] Alert marketing team to update downloads website with new links.
- [ ] Celebrate :tada:

**Comment by rhass** [comment]
I released 1.7.1 due to missing binaries for 1.7.0. I Think we can close this issue.
