### ISSUE TITLE
ecctl not supporting M1 Mac (darwin_arm64)

### ISSUE THREAD

**Issue by cgroschupp** [elastic/ecctl#544]
## Overview
ecctl not supporting M1 Mac (darwin_arm64)

## Possible Implementation
add arm64 to goreleaser archs.

## Context

This allow to run ecctl on ARM Macs

## Your Environment

`uname -a
Darwin cgroschupp 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64`

**Comment by henrikno** [comment]
Fixed by https://github.com/elastic/ecctl/pull/545
