### ISSUE TITLE
allocator vacate does not respect `--allocator-down`

### ISSUE THREAD

**Issue by Z3r0Sum** [elastic/ecctl#621]
Please see: https://github.com/elastic/cloud-sdk-go/pull/443

The problem is within the upstream cloud-sdk-go.

## Readiness Checklist

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I am reporting the issue to the correct repository (for multi-repository projects)

## Expected Behavior

I expect the query parameter for `allocator_down` to be set and leveraged by API - it is not.

## Current Behavior

The `platform allocator vacate` command with `--allocator-down true` is not set properly when making the request to the API.

## Steps to Reproduce

1. Run some variation of `ecctl platform allocator vacate <allocatord id> --allocator-down true`

## Possible Solution

See linked PR.

**Comment by Z3r0Sum** [comment]
@gigerdo / @tobio - This can be closed when we release the cloud-sdk-go + ecctl.  Are there plans to do so in the near future?  I think there's other related changes we want to pull in around ICs as well.

**Comment by gigerdo** [comment]
@Z3r0Sum I can release both :+1: 
What kind of changes to the ICs should also be released (I don't see any commits since the last release)

**Comment by gigerdo** [comment]
@Z3r0Sum the fix has been released with 1.11.0.
