### ISSUE TITLE
Support optional override_failsafe when doing a vacate (move_only) ES plan

### ISSUE THREAD

**Issue by jhalterman** [elastic/ecctl#77]
## Overview
It would be great if vacate/move_only plans could optionally override_failsafe since this is the current way of bypassing validations that can/will fail if a cluster is unhealthy and/or the allocator is unhealthy.

## Testing
Ensure that override_failsafe: true is passed in the transient section of the plan.

## Context
Without this it's not always possible to vacate unhealthy allocators.

**Comment by ppapapetrou76** [comment]
@jhalterman I want to add some context here
All vacates operated by the vanguard people are done almost automatically by `soteria` which means we are running `ecl` with a set of arguments that work in most cases. To my knowledge `override_failsafe` should not be used unless everything else doesn't work, right?
Please correct me if I'm wrong, the addition and usage of this flag is to allow people to resolve broken clusters, failed plans when there's nothing else left to try

/cc @elastic/cloud-sre-vanguard

**Comment by jhalterman** [comment]
override_failsafe will allow a plan to continue even when a step fails, so it should be used cautiously, but is often the only tool we have to signal the constructor to continue with a plan even when things are unavailable, such as a cluster or an allocator. This could help vacate a broken allocator, for example.
