### ISSUE TITLE
Creating deployment not available

### ISSUE THREAD

**Issue by liza-mae** [elastic/ecctl#90]
Hi 
I am using: 
https://download.elastic.co/downloads/ecctl/1.0.0-rc1/ecctl_1.0.0-rc1_linux_amd64.tar.gz

I would like to use it to create a deployment, I tried this command: 
./ecctl deployment create --file ../deploy.json --version  7.5.0 --track

Getting this error:
unknown flag: --file

I noticed the only options are create elasticsearch, create kibana or create apm, but I would like to create all from one file, how do I do this? 

Thanks.

**Comment by karencfv** [comment]
Hi @liza-mae! Thank you for opening up this issue.

This command has been [implemented](https://github.com/elastic/ecctl/blob/master/docs/ecctl_deployment_create.md) on the master branch and will be available in the next release.

If you'd like, you can build `ecctl` locally by following these [instructions](https://github.com/elastic/ecctl/blob/master/CONTRIBUTING.md#build-ecctl-locally-with-your-changes).

**Comment by marclop** [comment]
Thanks for opening issue Liza,

I think we should consider posting a disclaimer saying the master branch is always ahead of the documentation that's posted in the docs / website, since with the current docs it might be misleading as it is.

**Comment by liza-mae** [comment]
Thanks @karencfv @marclop ! 

Adding a disclaimer sounds great it would help.  I will try to build from source see how it goes, when will the next release be ?

**Comment by marclop** [comment]
@liza-mae We're looking at releasing later this week if all testing goes to plan.

**Comment by liza-mae** [comment]
Thanks @marclop - I was able to build ecctl successfully for now and I was able to create the deployment, Yay!  I really like the ease of use of ecctl :) 

We can close this issue.  Thanks again.
